package com.audiomack.model

enum class CellType {
    UNDEFINED, ACCOUNT, MUSIC_BROWSE_SMALL, MUSIC_BROWSE_SMALL_CHART, PLAYLIST, MUSIC_TINY, PLAYLIST_GRID, NOTIFICATION, NOTIFICATION_BUNDLED_PLAYLIST, FOOTER, EMPTY, HEADER
}
